language: node_js

node_js:
- 'stable'

dist: trusty

install: npm install

script:
  - npm run build

cache:
  directories:
    - node_modules

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  local-dir: './dist'
  fqdn: portfolio.zlepsi.me
  on:
    branch: master
